/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UserRouteImport } from './routes/user'
import { Route as TrajetsRouteImport } from './routes/trajets'
import { Route as RechercheRouteImport } from './routes/recherche'
import { Route as ProRouteImport } from './routes/pro'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RechercheIndexRouteImport } from './routes/recherche.index'
import { Route as UserParametreRouteImport } from './routes/user.parametre'
import { Route as RechercheResultatsRouteImport } from './routes/recherche.resultats'
import { Route as UserParametreZoneActiviteRouteImport } from './routes/user.parametre.zone-activite'
import { Route as UserParametreVehiculeRouteImport } from './routes/user.parametre.vehicule'
import { Route as UserParametreTranchesHorairesRouteImport } from './routes/user.parametre.tranches-horaires'

const UserRoute = UserRouteImport.update({
  id: '/user',
  path: '/user',
  getParentRoute: () => rootRouteImport,
} as any)
const TrajetsRoute = TrajetsRouteImport.update({
  id: '/trajets',
  path: '/trajets',
  getParentRoute: () => rootRouteImport,
} as any)
const RechercheRoute = RechercheRouteImport.update({
  id: '/recherche',
  path: '/recherche',
  getParentRoute: () => rootRouteImport,
} as any)
const ProRoute = ProRouteImport.update({
  id: '/pro',
  path: '/pro',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RechercheIndexRoute = RechercheIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => RechercheRoute,
} as any)
const UserParametreRoute = UserParametreRouteImport.update({
  id: '/parametre',
  path: '/parametre',
  getParentRoute: () => UserRoute,
} as any)
const RechercheResultatsRoute = RechercheResultatsRouteImport.update({
  id: '/resultats',
  path: '/resultats',
  getParentRoute: () => RechercheRoute,
} as any)
const UserParametreZoneActiviteRoute =
  UserParametreZoneActiviteRouteImport.update({
    id: '/zone-activite',
    path: '/zone-activite',
    getParentRoute: () => UserParametreRoute,
  } as any)
const UserParametreVehiculeRoute = UserParametreVehiculeRouteImport.update({
  id: '/vehicule',
  path: '/vehicule',
  getParentRoute: () => UserParametreRoute,
} as any)
const UserParametreTranchesHorairesRoute =
  UserParametreTranchesHorairesRouteImport.update({
    id: '/tranches-horaires',
    path: '/tranches-horaires',
    getParentRoute: () => UserParametreRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/pro': typeof ProRoute
  '/recherche': typeof RechercheRouteWithChildren
  '/trajets': typeof TrajetsRoute
  '/user': typeof UserRouteWithChildren
  '/recherche/resultats': typeof RechercheResultatsRoute
  '/user/parametre': typeof UserParametreRouteWithChildren
  '/recherche/': typeof RechercheIndexRoute
  '/user/parametre/tranches-horaires': typeof UserParametreTranchesHorairesRoute
  '/user/parametre/vehicule': typeof UserParametreVehiculeRoute
  '/user/parametre/zone-activite': typeof UserParametreZoneActiviteRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/pro': typeof ProRoute
  '/trajets': typeof TrajetsRoute
  '/user': typeof UserRouteWithChildren
  '/recherche/resultats': typeof RechercheResultatsRoute
  '/user/parametre': typeof UserParametreRouteWithChildren
  '/recherche': typeof RechercheIndexRoute
  '/user/parametre/tranches-horaires': typeof UserParametreTranchesHorairesRoute
  '/user/parametre/vehicule': typeof UserParametreVehiculeRoute
  '/user/parametre/zone-activite': typeof UserParametreZoneActiviteRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/pro': typeof ProRoute
  '/recherche': typeof RechercheRouteWithChildren
  '/trajets': typeof TrajetsRoute
  '/user': typeof UserRouteWithChildren
  '/recherche/resultats': typeof RechercheResultatsRoute
  '/user/parametre': typeof UserParametreRouteWithChildren
  '/recherche/': typeof RechercheIndexRoute
  '/user/parametre/tranches-horaires': typeof UserParametreTranchesHorairesRoute
  '/user/parametre/vehicule': typeof UserParametreVehiculeRoute
  '/user/parametre/zone-activite': typeof UserParametreZoneActiviteRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/pro'
    | '/recherche'
    | '/trajets'
    | '/user'
    | '/recherche/resultats'
    | '/user/parametre'
    | '/recherche/'
    | '/user/parametre/tranches-horaires'
    | '/user/parametre/vehicule'
    | '/user/parametre/zone-activite'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/pro'
    | '/trajets'
    | '/user'
    | '/recherche/resultats'
    | '/user/parametre'
    | '/recherche'
    | '/user/parametre/tranches-horaires'
    | '/user/parametre/vehicule'
    | '/user/parametre/zone-activite'
  id:
    | '__root__'
    | '/'
    | '/pro'
    | '/recherche'
    | '/trajets'
    | '/user'
    | '/recherche/resultats'
    | '/user/parametre'
    | '/recherche/'
    | '/user/parametre/tranches-horaires'
    | '/user/parametre/vehicule'
    | '/user/parametre/zone-activite'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProRoute: typeof ProRoute
  RechercheRoute: typeof RechercheRouteWithChildren
  TrajetsRoute: typeof TrajetsRoute
  UserRoute: typeof UserRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/user': {
      id: '/user'
      path: '/user'
      fullPath: '/user'
      preLoaderRoute: typeof UserRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trajets': {
      id: '/trajets'
      path: '/trajets'
      fullPath: '/trajets'
      preLoaderRoute: typeof TrajetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recherche': {
      id: '/recherche'
      path: '/recherche'
      fullPath: '/recherche'
      preLoaderRoute: typeof RechercheRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pro': {
      id: '/pro'
      path: '/pro'
      fullPath: '/pro'
      preLoaderRoute: typeof ProRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recherche/': {
      id: '/recherche/'
      path: '/'
      fullPath: '/recherche/'
      preLoaderRoute: typeof RechercheIndexRouteImport
      parentRoute: typeof RechercheRoute
    }
    '/user/parametre': {
      id: '/user/parametre'
      path: '/parametre'
      fullPath: '/user/parametre'
      preLoaderRoute: typeof UserParametreRouteImport
      parentRoute: typeof UserRoute
    }
    '/recherche/resultats': {
      id: '/recherche/resultats'
      path: '/resultats'
      fullPath: '/recherche/resultats'
      preLoaderRoute: typeof RechercheResultatsRouteImport
      parentRoute: typeof RechercheRoute
    }
    '/user/parametre/zone-activite': {
      id: '/user/parametre/zone-activite'
      path: '/zone-activite'
      fullPath: '/user/parametre/zone-activite'
      preLoaderRoute: typeof UserParametreZoneActiviteRouteImport
      parentRoute: typeof UserParametreRoute
    }
    '/user/parametre/vehicule': {
      id: '/user/parametre/vehicule'
      path: '/vehicule'
      fullPath: '/user/parametre/vehicule'
      preLoaderRoute: typeof UserParametreVehiculeRouteImport
      parentRoute: typeof UserParametreRoute
    }
    '/user/parametre/tranches-horaires': {
      id: '/user/parametre/tranches-horaires'
      path: '/tranches-horaires'
      fullPath: '/user/parametre/tranches-horaires'
      preLoaderRoute: typeof UserParametreTranchesHorairesRouteImport
      parentRoute: typeof UserParametreRoute
    }
  }
}

interface RechercheRouteChildren {
  RechercheResultatsRoute: typeof RechercheResultatsRoute
  RechercheIndexRoute: typeof RechercheIndexRoute
}

const RechercheRouteChildren: RechercheRouteChildren = {
  RechercheResultatsRoute: RechercheResultatsRoute,
  RechercheIndexRoute: RechercheIndexRoute,
}

const RechercheRouteWithChildren = RechercheRoute._addFileChildren(
  RechercheRouteChildren,
)

interface UserParametreRouteChildren {
  UserParametreTranchesHorairesRoute: typeof UserParametreTranchesHorairesRoute
  UserParametreVehiculeRoute: typeof UserParametreVehiculeRoute
  UserParametreZoneActiviteRoute: typeof UserParametreZoneActiviteRoute
}

const UserParametreRouteChildren: UserParametreRouteChildren = {
  UserParametreTranchesHorairesRoute: UserParametreTranchesHorairesRoute,
  UserParametreVehiculeRoute: UserParametreVehiculeRoute,
  UserParametreZoneActiviteRoute: UserParametreZoneActiviteRoute,
}

const UserParametreRouteWithChildren = UserParametreRoute._addFileChildren(
  UserParametreRouteChildren,
)

interface UserRouteChildren {
  UserParametreRoute: typeof UserParametreRouteWithChildren
}

const UserRouteChildren: UserRouteChildren = {
  UserParametreRoute: UserParametreRouteWithChildren,
}

const UserRouteWithChildren = UserRoute._addFileChildren(UserRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProRoute: ProRoute,
  RechercheRoute: RechercheRouteWithChildren,
  TrajetsRoute: TrajetsRoute,
  UserRoute: UserRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
